# READ THE FILE

# GET THE FILE NAME
# CREATE A NEW FILE IF NEEDED AND CREATE A CONDITIONAL THAT CHECKS IF THE FILE ALREADY EXISTS

# GET THE HEADERS
# ADD THEM TO AN ARRAY
# WRITE THE LINE IN THE FILE

# GET THE LINES
# MAKE A FOR LOOP

# GENERATE EACH TYPE OF VARIABLE ACCORDINGLY
# ->    Random Int
# ->    Random String in array
# ->    Random time (HOUR:MINUTES:SECONDS)
# ADD THEM TO AN ARRAY
# WRITE THE LINE IN THE FILE